// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWcH92KhF022qsTXZMbWw1DuhE721k1To',
    appId: '1:1072814174682:web:0b9aecc0fe2dd45e1cd0e3',
    messagingSenderId: '1072814174682',
    projectId: 'notes-auth-8b56f',
    authDomain: 'notes-auth-8b56f.firebaseapp.com',
    storageBucket: 'notes-auth-8b56f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzq1g2nTsAQBZJQgGF0x2R0063A9r9_4',
    appId: '1:1072814174682:android:8240541e6beb6f711cd0e3',
    messagingSenderId: '1072814174682',
    projectId: 'notes-auth-8b56f',
    storageBucket: 'notes-auth-8b56f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCougPjrmDW259Cydg6b2y7Wy8GSyObcPw',
    appId: '1:1072814174682:ios:afcb1c3c39a09aeb1cd0e3',
    messagingSenderId: '1072814174682',
    projectId: 'notes-auth-8b56f',
    storageBucket: 'notes-auth-8b56f.appspot.com',
    iosClientId: '1072814174682-28dp052277nfnonklc1qt3de42614l0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudOperation',
  );
}
